// This file was generated by rgen
// Project: Slippy.xcodeproj
// Target : Slippy

@class RGenImagesRoot;
@class RGenImagesRootImages;
@class RGenImagesRootTiles;
@class RGenImagesRootImagesNormal;
@class RGenImagesRootImagesPreview;

@class RGenPathsRoot;
@class RGenPathsRootAudio;
@class RGenPathsRootImages;
@class RGenPathsRootTiles;
@class RGenPathsRootImagesNormal;
@class RGenPathsRootImagesPreview;
@class RGenPathsRootLevels;
@class RGenPathsRootSettingsbundle;
@class RGenPathsRootEnlproj;

RGenImagesRoot *I;

@interface DescriptionString : NSString
@end

RGenPathsRoot *P;

@interface RGenImagesRoot : NSObject {
  UIImage *default2xipad;
  UIImage *defaultLandscape;
  UIImage *defaultLandscape2xipad;
  UIImage *defaultLandscapeipad;
  UIImage *default_;
  UIImage *defaultipad;
  UIImage *icon;
  UIImage *icon2xipad;
  UIImage *icon72;
  UIImage *iconSmall;
  UIImage *iconSmall50;
  UIImage *iconipad;
  RGenImagesRootImages *images;
}

@property(nonatomic, readonly) UIImage *default2xipad; //!< Default@2x~ipad.png
@property(nonatomic, readonly) UIImage *defaultLandscape; //!< Default-Landscape.png
@property(nonatomic, readonly) UIImage *defaultLandscape2xipad; //!< Default-Landscape@2x~ipad.png
@property(nonatomic, readonly) UIImage *defaultLandscapeipad; //!< Default-Landscape~ipad.png
@property(nonatomic, readonly) UIImage *default_; //!< Default.png
@property(nonatomic, readonly) UIImage *defaultipad; //!< Default~ipad.png
@property(nonatomic, readonly) UIImage *icon; //!< Icon.png
@property(nonatomic, readonly) UIImage *icon2xipad; //!< Icon@2x~ipad.png
@property(nonatomic, readonly) UIImage *icon72; //!< Icon-72.png
@property(nonatomic, readonly) UIImage *iconSmall; //!< Icon-Small.png
@property(nonatomic, readonly) UIImage *iconSmall50; //!< Icon-Small-50.png
@property(nonatomic, readonly) UIImage *iconipad; //!< Icon~ipad.png
@property(nonatomic, readonly) RGenImagesRootImages *images; //!< images

//! Load and retain images recursively
- (void)loadImages;
//! Release images recursively
- (void)releaseImages;

@end

@interface RGenImagesRootImages : NSObject {
  UIImage *background;
  UIImage *background2xipad;
  UIImage *backgroundipad;
  UIImage *bigStarsBorderEmpty;
  UIImage *bigStarsBorderEmpty2xipad;
  UIImage *bigStarsBorderEmptyipad;
  UIImage *bigStarsBorderFull;
  UIImage *bigStarsBorderFull2xipad;
  UIImage *bigStarsBorderFullipad;
  UIImage *bigStarsBorderHalf;
  UIImage *bigStarsBorderHalf2xipad;
  UIImage *bigStarsBorderHalfipad;
  UIImage *bigStarsEmpty;
  UIImage *bigStarsEmpty2xipad;
  UIImage *bigStarsEmptyipad;
  UIImage *bigStarsFull;
  UIImage *bigStarsFull2xipad;
  UIImage *bigStarsFullipad;
  UIImage *bigStarsHalf;
  UIImage *bigStarsHalf2xipad;
  UIImage *bigStarsHalfipad;
  UIImage *block;
  UIImage *block2xipad;
  UIImage *blockipad;
  UIImage *check;
  UIImage *check2xipad;
  UIImage *checkipad;
  UIImage *close;
  UIImage *close2xipad;
  UIImage *closeipad;
  UIImage *community;
  UIImage *community2xipad;
  UIImage *communityipad;
  UIImage *completed;
  UIImage *completed2xipad;
  UIImage *completedipad;
  UIImage *delete2xipad;
  UIImage *delete_;
  UIImage *deleteipad;
  UIImage *disable;
  UIImage *disable2xipad;
  UIImage *disableipad;
  UIImage *dot;
  UIImage *dot2xipad;
  UIImage *dotipad;
  UIImage *download;
  UIImage *download2xipad;
  UIImage *downloadRain;
  UIImage *downloadRain2xipad;
  UIImage *downloadRainipad;
  UIImage *downloadSun;
  UIImage *downloadSun2xipad;
  UIImage *downloadSunipad;
  UIImage *downloadipad;
  UIImage *dpad;
  UIImage *dpad2xipad;
  UIImage *dpadIcon;
  UIImage *dpadIcon2xipad;
  UIImage *dpadIconipad;
  UIImage *dpadTouch;
  UIImage *dpadTouch2xipad;
  UIImage *dpadTouchipad;
  UIImage *dpadipad;
  UIImage *effect;
  UIImage *effect2xipad;
  UIImage *effectipad;
  UIImage *erase;
  UIImage *erase2xipad;
  UIImage *eraseipad;
  UIImage *handPoint;
  UIImage *handPoint2xipad;
  UIImage *handPointipad;
  UIImage *handTouch;
  UIImage *handTouch2xipad;
  UIImage *handTouchipad;
  UIImage *left;
  UIImage *left2xipad;
  UIImage *leftipad;
  UIImage *menuAbout;
  UIImage *menuAbout2xipad;
  UIImage *menuAboutipad;
  UIImage *menuOverlay;
  UIImage *menuOverlay2xipad;
  UIImage *menuOverlayipad;
  UIImage *menuPlay;
  UIImage *menuPlay2xipad;
  UIImage *menuPlayipad;
  UIImage *menuSlippy;
  UIImage *menuSlippy2xipad;
  UIImage *menuSlippyBlink;
  UIImage *menuSlippyBlink2xipad;
  UIImage *menuSlippyBlinkipad;
  UIImage *menuSlippyipad;
  UIImage *menuTutorial;
  UIImage *menuTutorial2xipad;
  UIImage *menuTutorialipad;
  UIImage *menuYourLevels;
  UIImage *menuYourLevels2xipad;
  UIImage *menuYourLevelsipad;
  UIImage *moveable;
  UIImage *moveable2xipad;
  UIImage *moveableipad;
  UIImage *music;
  UIImage *music2xipad;
  UIImage *musicipad;
  UIImage *new2xipad;
  UIImage *new_;
  UIImage *newipad;
  UIImage *original;
  UIImage *original2xipad;
  UIImage *originalipad;
  UIImage *play;
  UIImage *play2xipad;
  UIImage *player;
  UIImage *player2xipad;
  UIImage *playerFrames;
  UIImage *playerFrames2xipad;
  UIImage *playerFramesipad;
  UIImage *playeripad;
  UIImage *playipad;
  UIImage *plus;
  UIImage *plus2xipad;
  UIImage *plusipad;
  UIImage *restart;
  UIImage *restart2xipad;
  UIImage *restartipad;
  UIImage *right;
  UIImage *right2xipad;
  UIImage *rightipad;
  UIImage *scaleBars;
  UIImage *scaleBars2xipad;
  UIImage *scaleBarsipad;
  UIImage *scaleFade;
  UIImage *scaleFade2xipad;
  UIImage *scaleFadeipad;
  UIImage *score;
  UIImage *score2xipad;
  UIImage *scoreipad;
  UIImage *slippy;
  UIImage *slippy2xipad;
  UIImage *slippyipad;
  UIImage *solid;
  UIImage *solid2xipad;
  UIImage *solidipad;
  UIImage *starsBorderEmpty;
  UIImage *starsBorderEmpty2xipad;
  UIImage *starsBorderEmptyipad;
  UIImage *starsBorderFull;
  UIImage *starsBorderFull2xipad;
  UIImage *starsBorderFullipad;
  UIImage *starsBorderHalf;
  UIImage *starsBorderHalf2xipad;
  UIImage *starsBorderHalfipad;
  UIImage *starsEmpty;
  UIImage *starsEmpty2xipad;
  UIImage *starsEmptyipad;
  UIImage *starsFull;
  UIImage *starsFull2xipad;
  UIImage *starsFullipad;
  UIImage *starsHalf;
  UIImage *starsHalf2xipad;
  UIImage *starsHalfipad;
  RGenImagesRootTiles *tiles;
  UIImage *undo;
  UIImage *undo2xipad;
  UIImage *undoipad;
  UIImage *upload;
  UIImage *upload2xipad;
  UIImage *uploadCheck;
  UIImage *uploadCheck2xipad;
  UIImage *uploadCheckipad;
  UIImage *uploadRain;
  UIImage *uploadRain2xipad;
  UIImage *uploadRainipad;
  UIImage *uploadSun;
  UIImage *uploadSun2xipad;
  UIImage *uploadSunipad;
  UIImage *uploadipad;
  UIImage *water;
  UIImage *water2xipad;
  UIImage *wateripad;
}

@property(nonatomic, readonly) UIImage *background; //!< images/background.png
@property(nonatomic, readonly) UIImage *background2xipad; //!< images/background@2x~ipad.png
@property(nonatomic, readonly) UIImage *backgroundipad; //!< images/background~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsBorderEmpty; //!< images/big-stars-border-empty.png
@property(nonatomic, readonly) UIImage *bigStarsBorderEmpty2xipad; //!< images/big-stars-border-empty@2x~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsBorderEmptyipad; //!< images/big-stars-border-empty~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsBorderFull; //!< images/big-stars-border-full.png
@property(nonatomic, readonly) UIImage *bigStarsBorderFull2xipad; //!< images/big-stars-border-full@2x~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsBorderFullipad; //!< images/big-stars-border-full~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsBorderHalf; //!< images/big-stars-border-half.png
@property(nonatomic, readonly) UIImage *bigStarsBorderHalf2xipad; //!< images/big-stars-border-half@2x~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsBorderHalfipad; //!< images/big-stars-border-half~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsEmpty; //!< images/big-stars-empty.png
@property(nonatomic, readonly) UIImage *bigStarsEmpty2xipad; //!< images/big-stars-empty@2x~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsEmptyipad; //!< images/big-stars-empty~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsFull; //!< images/big-stars-full.png
@property(nonatomic, readonly) UIImage *bigStarsFull2xipad; //!< images/big-stars-full@2x~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsFullipad; //!< images/big-stars-full~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsHalf; //!< images/big-stars-half.png
@property(nonatomic, readonly) UIImage *bigStarsHalf2xipad; //!< images/big-stars-half@2x~ipad.png
@property(nonatomic, readonly) UIImage *bigStarsHalfipad; //!< images/big-stars-half~ipad.png
@property(nonatomic, readonly) UIImage *block; //!< images/block.png
@property(nonatomic, readonly) UIImage *block2xipad; //!< images/block@2x~ipad.png
@property(nonatomic, readonly) UIImage *blockipad; //!< images/block~ipad.png
@property(nonatomic, readonly) UIImage *check; //!< images/check.png
@property(nonatomic, readonly) UIImage *check2xipad; //!< images/check@2x~ipad.png
@property(nonatomic, readonly) UIImage *checkipad; //!< images/check~ipad.png
@property(nonatomic, readonly) UIImage *close; //!< images/close.png
@property(nonatomic, readonly) UIImage *close2xipad; //!< images/close@2x~ipad.png
@property(nonatomic, readonly) UIImage *closeipad; //!< images/close~ipad.png
@property(nonatomic, readonly) UIImage *community; //!< images/community.png
@property(nonatomic, readonly) UIImage *community2xipad; //!< images/community@2x~ipad.png
@property(nonatomic, readonly) UIImage *communityipad; //!< images/community~ipad.png
@property(nonatomic, readonly) UIImage *completed; //!< images/completed.png
@property(nonatomic, readonly) UIImage *completed2xipad; //!< images/completed@2x~ipad.png
@property(nonatomic, readonly) UIImage *completedipad; //!< images/completed~ipad.png
@property(nonatomic, readonly) UIImage *delete2xipad; //!< images/delete@2x~ipad.png
@property(nonatomic, readonly) UIImage *delete_; //!< images/delete.png
@property(nonatomic, readonly) UIImage *deleteipad; //!< images/delete~ipad.png
@property(nonatomic, readonly) UIImage *disable; //!< images/disable.png
@property(nonatomic, readonly) UIImage *disable2xipad; //!< images/disable@2x~ipad.png
@property(nonatomic, readonly) UIImage *disableipad; //!< images/disable~ipad.png
@property(nonatomic, readonly) UIImage *dot; //!< images/dot.png
@property(nonatomic, readonly) UIImage *dot2xipad; //!< images/dot@2x~ipad.png
@property(nonatomic, readonly) UIImage *dotipad; //!< images/dot~ipad.png
@property(nonatomic, readonly) UIImage *download; //!< images/download.png
@property(nonatomic, readonly) UIImage *download2xipad; //!< images/download@2x~ipad.png
@property(nonatomic, readonly) UIImage *downloadRain; //!< images/download-rain.png
@property(nonatomic, readonly) UIImage *downloadRain2xipad; //!< images/download-rain@2x~ipad.png
@property(nonatomic, readonly) UIImage *downloadRainipad; //!< images/download-rain~ipad.png
@property(nonatomic, readonly) UIImage *downloadSun; //!< images/download-sun.png
@property(nonatomic, readonly) UIImage *downloadSun2xipad; //!< images/download-sun@2x~ipad.png
@property(nonatomic, readonly) UIImage *downloadSunipad; //!< images/download-sun~ipad.png
@property(nonatomic, readonly) UIImage *downloadipad; //!< images/download~ipad.png
@property(nonatomic, readonly) UIImage *dpad; //!< images/dpad.png
@property(nonatomic, readonly) UIImage *dpad2xipad; //!< images/dpad@2x~ipad.png
@property(nonatomic, readonly) UIImage *dpadIcon; //!< images/dpad-icon.png
@property(nonatomic, readonly) UIImage *dpadIcon2xipad; //!< images/dpad-icon@2x~ipad.png
@property(nonatomic, readonly) UIImage *dpadIconipad; //!< images/dpad-icon~ipad.png
@property(nonatomic, readonly) UIImage *dpadTouch; //!< images/dpad-touch.png
@property(nonatomic, readonly) UIImage *dpadTouch2xipad; //!< images/dpad-touch@2x~ipad.png
@property(nonatomic, readonly) UIImage *dpadTouchipad; //!< images/dpad-touch~ipad.png
@property(nonatomic, readonly) UIImage *dpadipad; //!< images/dpad~ipad.png
@property(nonatomic, readonly) UIImage *effect; //!< images/effect.png
@property(nonatomic, readonly) UIImage *effect2xipad; //!< images/effect@2x~ipad.png
@property(nonatomic, readonly) UIImage *effectipad; //!< images/effect~ipad.png
@property(nonatomic, readonly) UIImage *erase; //!< images/erase.png
@property(nonatomic, readonly) UIImage *erase2xipad; //!< images/erase@2x~ipad.png
@property(nonatomic, readonly) UIImage *eraseipad; //!< images/erase~ipad.png
@property(nonatomic, readonly) UIImage *handPoint; //!< images/hand-point.png
@property(nonatomic, readonly) UIImage *handPoint2xipad; //!< images/hand-point@2x~ipad.png
@property(nonatomic, readonly) UIImage *handPointipad; //!< images/hand-point~ipad.png
@property(nonatomic, readonly) UIImage *handTouch; //!< images/hand-touch.png
@property(nonatomic, readonly) UIImage *handTouch2xipad; //!< images/hand-touch@2x~ipad.png
@property(nonatomic, readonly) UIImage *handTouchipad; //!< images/hand-touch~ipad.png
@property(nonatomic, readonly) UIImage *left; //!< images/left.png
@property(nonatomic, readonly) UIImage *left2xipad; //!< images/left@2x~ipad.png
@property(nonatomic, readonly) UIImage *leftipad; //!< images/left~ipad.png
@property(nonatomic, readonly) UIImage *menuAbout; //!< images/menu-about.png
@property(nonatomic, readonly) UIImage *menuAbout2xipad; //!< images/menu-about@2x~ipad.png
@property(nonatomic, readonly) UIImage *menuAboutipad; //!< images/menu-about~ipad.png
@property(nonatomic, readonly) UIImage *menuOverlay; //!< images/menu-overlay.png
@property(nonatomic, readonly) UIImage *menuOverlay2xipad; //!< images/menu-overlay@2x~ipad.png
@property(nonatomic, readonly) UIImage *menuOverlayipad; //!< images/menu-overlay~ipad.png
@property(nonatomic, readonly) UIImage *menuPlay; //!< images/menu-play.png
@property(nonatomic, readonly) UIImage *menuPlay2xipad; //!< images/menu-play@2x~ipad.png
@property(nonatomic, readonly) UIImage *menuPlayipad; //!< images/menu-play~ipad.png
@property(nonatomic, readonly) UIImage *menuSlippy; //!< images/menu-slippy.png
@property(nonatomic, readonly) UIImage *menuSlippy2xipad; //!< images/menu-slippy@2x~ipad.png
@property(nonatomic, readonly) UIImage *menuSlippyBlink; //!< images/menu-slippy-blink.png
@property(nonatomic, readonly) UIImage *menuSlippyBlink2xipad; //!< images/menu-slippy-blink@2x~ipad.png
@property(nonatomic, readonly) UIImage *menuSlippyBlinkipad; //!< images/menu-slippy-blink~ipad.png
@property(nonatomic, readonly) UIImage *menuSlippyipad; //!< images/menu-slippy~ipad.png
@property(nonatomic, readonly) UIImage *menuTutorial; //!< images/menu-tutorial.png
@property(nonatomic, readonly) UIImage *menuTutorial2xipad; //!< images/menu-tutorial@2x~ipad.png
@property(nonatomic, readonly) UIImage *menuTutorialipad; //!< images/menu-tutorial~ipad.png
@property(nonatomic, readonly) UIImage *menuYourLevels; //!< images/menu-your-levels.png
@property(nonatomic, readonly) UIImage *menuYourLevels2xipad; //!< images/menu-your-levels@2x~ipad.png
@property(nonatomic, readonly) UIImage *menuYourLevelsipad; //!< images/menu-your-levels~ipad.png
@property(nonatomic, readonly) UIImage *moveable; //!< images/moveable.png
@property(nonatomic, readonly) UIImage *moveable2xipad; //!< images/moveable@2x~ipad.png
@property(nonatomic, readonly) UIImage *moveableipad; //!< images/moveable~ipad.png
@property(nonatomic, readonly) UIImage *music; //!< images/music.png
@property(nonatomic, readonly) UIImage *music2xipad; //!< images/music@2x~ipad.png
@property(nonatomic, readonly) UIImage *musicipad; //!< images/music~ipad.png
@property(nonatomic, readonly) UIImage *new2xipad; //!< images/new@2x~ipad.png
@property(nonatomic, readonly) UIImage *new_; //!< images/new.png
@property(nonatomic, readonly) UIImage *newipad; //!< images/new~ipad.png
@property(nonatomic, readonly) UIImage *original; //!< images/original.png
@property(nonatomic, readonly) UIImage *original2xipad; //!< images/original@2x~ipad.png
@property(nonatomic, readonly) UIImage *originalipad; //!< images/original~ipad.png
@property(nonatomic, readonly) UIImage *play; //!< images/play.png
@property(nonatomic, readonly) UIImage *play2xipad; //!< images/play@2x~ipad.png
@property(nonatomic, readonly) UIImage *player; //!< images/player.png
@property(nonatomic, readonly) UIImage *player2xipad; //!< images/player@2x~ipad.png
@property(nonatomic, readonly) UIImage *playerFrames; //!< images/player-frames.png
@property(nonatomic, readonly) UIImage *playerFrames2xipad; //!< images/player-frames@2x~ipad.png
@property(nonatomic, readonly) UIImage *playerFramesipad; //!< images/player-frames~ipad.png
@property(nonatomic, readonly) UIImage *playeripad; //!< images/player~ipad.png
@property(nonatomic, readonly) UIImage *playipad; //!< images/play~ipad.png
@property(nonatomic, readonly) UIImage *plus; //!< images/plus.png
@property(nonatomic, readonly) UIImage *plus2xipad; //!< images/plus@2x~ipad.png
@property(nonatomic, readonly) UIImage *plusipad; //!< images/plus~ipad.png
@property(nonatomic, readonly) UIImage *restart; //!< images/restart.png
@property(nonatomic, readonly) UIImage *restart2xipad; //!< images/restart@2x~ipad.png
@property(nonatomic, readonly) UIImage *restartipad; //!< images/restart~ipad.png
@property(nonatomic, readonly) UIImage *right; //!< images/right.png
@property(nonatomic, readonly) UIImage *right2xipad; //!< images/right@2x~ipad.png
@property(nonatomic, readonly) UIImage *rightipad; //!< images/right~ipad.png
@property(nonatomic, readonly) UIImage *scaleBars; //!< images/scale-bars.png
@property(nonatomic, readonly) UIImage *scaleBars2xipad; //!< images/scale-bars@2x~ipad.png
@property(nonatomic, readonly) UIImage *scaleBarsipad; //!< images/scale-bars~ipad.png
@property(nonatomic, readonly) UIImage *scaleFade; //!< images/scale-fade.png
@property(nonatomic, readonly) UIImage *scaleFade2xipad; //!< images/scale-fade@2x~ipad.png
@property(nonatomic, readonly) UIImage *scaleFadeipad; //!< images/scale-fade~ipad.png
@property(nonatomic, readonly) UIImage *score; //!< images/score.png
@property(nonatomic, readonly) UIImage *score2xipad; //!< images/score@2x~ipad.png
@property(nonatomic, readonly) UIImage *scoreipad; //!< images/score~ipad.png
@property(nonatomic, readonly) UIImage *slippy; //!< images/slippy.png
@property(nonatomic, readonly) UIImage *slippy2xipad; //!< images/slippy@2x~ipad.png
@property(nonatomic, readonly) UIImage *slippyipad; //!< images/slippy~ipad.png
@property(nonatomic, readonly) UIImage *solid; //!< images/solid.png
@property(nonatomic, readonly) UIImage *solid2xipad; //!< images/solid@2x~ipad.png
@property(nonatomic, readonly) UIImage *solidipad; //!< images/solid~ipad.png
@property(nonatomic, readonly) UIImage *starsBorderEmpty; //!< images/stars-border-empty.png
@property(nonatomic, readonly) UIImage *starsBorderEmpty2xipad; //!< images/stars-border-empty@2x~ipad.png
@property(nonatomic, readonly) UIImage *starsBorderEmptyipad; //!< images/stars-border-empty~ipad.png
@property(nonatomic, readonly) UIImage *starsBorderFull; //!< images/stars-border-full.png
@property(nonatomic, readonly) UIImage *starsBorderFull2xipad; //!< images/stars-border-full@2x~ipad.png
@property(nonatomic, readonly) UIImage *starsBorderFullipad; //!< images/stars-border-full~ipad.png
@property(nonatomic, readonly) UIImage *starsBorderHalf; //!< images/stars-border-half.png
@property(nonatomic, readonly) UIImage *starsBorderHalf2xipad; //!< images/stars-border-half@2x~ipad.png
@property(nonatomic, readonly) UIImage *starsBorderHalfipad; //!< images/stars-border-half~ipad.png
@property(nonatomic, readonly) UIImage *starsEmpty; //!< images/stars-empty.png
@property(nonatomic, readonly) UIImage *starsEmpty2xipad; //!< images/stars-empty@2x~ipad.png
@property(nonatomic, readonly) UIImage *starsEmptyipad; //!< images/stars-empty~ipad.png
@property(nonatomic, readonly) UIImage *starsFull; //!< images/stars-full.png
@property(nonatomic, readonly) UIImage *starsFull2xipad; //!< images/stars-full@2x~ipad.png
@property(nonatomic, readonly) UIImage *starsFullipad; //!< images/stars-full~ipad.png
@property(nonatomic, readonly) UIImage *starsHalf; //!< images/stars-half.png
@property(nonatomic, readonly) UIImage *starsHalf2xipad; //!< images/stars-half@2x~ipad.png
@property(nonatomic, readonly) UIImage *starsHalfipad; //!< images/stars-half~ipad.png
@property(nonatomic, readonly) RGenImagesRootTiles *tiles; //!< images/tiles
@property(nonatomic, readonly) UIImage *undo; //!< images/undo.png
@property(nonatomic, readonly) UIImage *undo2xipad; //!< images/undo@2x~ipad.png
@property(nonatomic, readonly) UIImage *undoipad; //!< images/undo~ipad.png
@property(nonatomic, readonly) UIImage *upload; //!< images/upload.png
@property(nonatomic, readonly) UIImage *upload2xipad; //!< images/upload@2x~ipad.png
@property(nonatomic, readonly) UIImage *uploadCheck; //!< images/upload-check.png
@property(nonatomic, readonly) UIImage *uploadCheck2xipad; //!< images/upload-check@2x~ipad.png
@property(nonatomic, readonly) UIImage *uploadCheckipad; //!< images/upload-check~ipad.png
@property(nonatomic, readonly) UIImage *uploadRain; //!< images/upload-rain.png
@property(nonatomic, readonly) UIImage *uploadRain2xipad; //!< images/upload-rain@2x~ipad.png
@property(nonatomic, readonly) UIImage *uploadRainipad; //!< images/upload-rain~ipad.png
@property(nonatomic, readonly) UIImage *uploadSun; //!< images/upload-sun.png
@property(nonatomic, readonly) UIImage *uploadSun2xipad; //!< images/upload-sun@2x~ipad.png
@property(nonatomic, readonly) UIImage *uploadSunipad; //!< images/upload-sun~ipad.png
@property(nonatomic, readonly) UIImage *uploadipad; //!< images/upload~ipad.png
@property(nonatomic, readonly) UIImage *water; //!< images/water.png
@property(nonatomic, readonly) UIImage *water2xipad; //!< images/water@2x~ipad.png
@property(nonatomic, readonly) UIImage *wateripad; //!< images/water~ipad.png

//! Load and retain images recursively
- (void)loadImages;
//! Release images recursively
- (void)releaseImages;

@end

@interface RGenImagesRootTiles : NSObject {
  RGenImagesRootImagesNormal *normal;
  RGenImagesRootImagesPreview *preview;
}

@property(nonatomic, readonly) RGenImagesRootImagesNormal *normal; //!< images/tiles/normal
@property(nonatomic, readonly) RGenImagesRootImagesPreview *preview; //!< images/tiles/preview

//! Load and retain images recursively
- (void)loadImages;
//! Release images recursively
- (void)releaseImages;

@end

@interface RGenImagesRootImagesNormal : NSObject {
  UIImage *block;
  UIImage *block2xipad;
  UIImage *blockMask;
  UIImage *blockMask2xipad;
  UIImage *blockMaskipad;
  UIImage *blockipad;
  UIImage *moveable;
  UIImage *moveable2xipad;
  UIImage *moveableipad;
  UIImage *player;
  UIImage *player2xipad;
  UIImage *playeripad;
  UIImage *score;
  UIImage *score2xipad;
  UIImage *scoreipad;
  UIImage *solid;
  UIImage *solid2xipad;
  UIImage *solidipad;
}

@property(nonatomic, readonly) UIImage *block; //!< images/tiles/normal/block.png
@property(nonatomic, readonly) UIImage *block2xipad; //!< images/tiles/normal/block@2x~ipad.png
@property(nonatomic, readonly) UIImage *blockMask; //!< images/tiles/normal/block-mask.png
@property(nonatomic, readonly) UIImage *blockMask2xipad; //!< images/tiles/normal/block-mask@2x~ipad.png
@property(nonatomic, readonly) UIImage *blockMaskipad; //!< images/tiles/normal/block-mask~ipad.png
@property(nonatomic, readonly) UIImage *blockipad; //!< images/tiles/normal/block~ipad.png
@property(nonatomic, readonly) UIImage *moveable; //!< images/tiles/normal/moveable.png
@property(nonatomic, readonly) UIImage *moveable2xipad; //!< images/tiles/normal/moveable@2x~ipad.png
@property(nonatomic, readonly) UIImage *moveableipad; //!< images/tiles/normal/moveable~ipad.png
@property(nonatomic, readonly) UIImage *player; //!< images/tiles/normal/player.png
@property(nonatomic, readonly) UIImage *player2xipad; //!< images/tiles/normal/player@2x~ipad.png
@property(nonatomic, readonly) UIImage *playeripad; //!< images/tiles/normal/player~ipad.png
@property(nonatomic, readonly) UIImage *score; //!< images/tiles/normal/score.png
@property(nonatomic, readonly) UIImage *score2xipad; //!< images/tiles/normal/score@2x~ipad.png
@property(nonatomic, readonly) UIImage *scoreipad; //!< images/tiles/normal/score~ipad.png
@property(nonatomic, readonly) UIImage *solid; //!< images/tiles/normal/solid.png
@property(nonatomic, readonly) UIImage *solid2xipad; //!< images/tiles/normal/solid@2x~ipad.png
@property(nonatomic, readonly) UIImage *solidipad; //!< images/tiles/normal/solid~ipad.png

//! Load and retain images recursively
- (void)loadImages;
//! Release images recursively
- (void)releaseImages;

@end

@interface RGenImagesRootImagesPreview : NSObject {
  UIImage *block;
  UIImage *block2xipad;
  UIImage *blockipad;
  UIImage *moveable;
  UIImage *moveable2xipad;
  UIImage *moveableipad;
  UIImage *player;
  UIImage *player2xipad;
  UIImage *playeripad;
  UIImage *score;
  UIImage *score2xipad;
  UIImage *scoreipad;
  UIImage *solid;
  UIImage *solid2xipad;
  UIImage *solidipad;
}

@property(nonatomic, readonly) UIImage *block; //!< images/tiles/preview/block.png
@property(nonatomic, readonly) UIImage *block2xipad; //!< images/tiles/preview/block@2x~ipad.png
@property(nonatomic, readonly) UIImage *blockipad; //!< images/tiles/preview/block~ipad.png
@property(nonatomic, readonly) UIImage *moveable; //!< images/tiles/preview/moveable.png
@property(nonatomic, readonly) UIImage *moveable2xipad; //!< images/tiles/preview/moveable@2x~ipad.png
@property(nonatomic, readonly) UIImage *moveableipad; //!< images/tiles/preview/moveable~ipad.png
@property(nonatomic, readonly) UIImage *player; //!< images/tiles/preview/player.png
@property(nonatomic, readonly) UIImage *player2xipad; //!< images/tiles/preview/player@2x~ipad.png
@property(nonatomic, readonly) UIImage *playeripad; //!< images/tiles/preview/player~ipad.png
@property(nonatomic, readonly) UIImage *score; //!< images/tiles/preview/score.png
@property(nonatomic, readonly) UIImage *score2xipad; //!< images/tiles/preview/score@2x~ipad.png
@property(nonatomic, readonly) UIImage *scoreipad; //!< images/tiles/preview/score~ipad.png
@property(nonatomic, readonly) UIImage *solid; //!< images/tiles/preview/solid.png
@property(nonatomic, readonly) UIImage *solid2xipad; //!< images/tiles/preview/solid@2x~ipad.png
@property(nonatomic, readonly) UIImage *solidipad; //!< images/tiles/preview/solid~ipad.png

//! Load and retain images recursively
- (void)loadImages;
//! Release images recursively
- (void)releaseImages;

@end

@interface RGenPathsRoot : DescriptionString {
  RGenPathsRootAudio *audio;
  RGenPathsRootImages *images;
  RGenPathsRootLevels *levels;
  RGenPathsRootSettingsbundle *settingsBundle;
}

@property(nonatomic, readonly) NSString *aboutHtml; //!< about.html
@property(nonatomic, readonly) RGenPathsRootAudio *audio; //!< audio
@property(nonatomic, readonly) NSString *default2xPng; //!< Default@2x.png
@property(nonatomic, readonly) NSString *default2xipadPng; //!< Default@2x~ipad.png
@property(nonatomic, readonly) NSString *defaultLandscape2xPng; //!< Default-Landscape@2x.png
@property(nonatomic, readonly) NSString *defaultLandscape2xipadPng; //!< Default-Landscape@2x~ipad.png
@property(nonatomic, readonly) NSString *defaultLandscapePng; //!< Default-Landscape.png
@property(nonatomic, readonly) NSString *defaultLandscapeipadPng; //!< Default-Landscape~ipad.png
@property(nonatomic, readonly) NSString *defaultPng; //!< Default.png
@property(nonatomic, readonly) NSString *defaultipadPng; //!< Default~ipad.png
@property(nonatomic, readonly) NSString *iTunesArtwork; //!< iTunesArtwork
@property(nonatomic, readonly) NSString *iTunesArtwork2x; //!< iTunesArtwork@2x
@property(nonatomic, readonly) NSString *icon2xPng; //!< Icon@2x.png
@property(nonatomic, readonly) NSString *icon2xipadPng; //!< Icon@2x~ipad.png
@property(nonatomic, readonly) NSString *icon722xPng; //!< Icon-72@2x.png
@property(nonatomic, readonly) NSString *icon72Png; //!< Icon-72.png
@property(nonatomic, readonly) NSString *iconPng; //!< Icon.png
@property(nonatomic, readonly) NSString *iconSmall2xPng; //!< Icon-Small@2x.png
@property(nonatomic, readonly) NSString *iconSmall502xPng; //!< Icon-Small-50@2x.png
@property(nonatomic, readonly) NSString *iconSmall50Png; //!< Icon-Small-50.png
@property(nonatomic, readonly) NSString *iconSmallPng; //!< Icon-Small.png
@property(nonatomic, readonly) NSString *iconipadPng; //!< Icon~ipad.png
@property(nonatomic, readonly) RGenPathsRootImages *images; //!< images
@property(nonatomic, readonly) RGenPathsRootLevels *levels; //!< levels
@property(nonatomic, readonly) RGenPathsRootSettingsbundle *settingsBundle; //!< Settings.bundle

@end

@interface RGenPathsRootAudio : DescriptionString
@property(nonatomic, readonly) NSString *blockblockWav; //!< audio/blockblock.wav
@property(nonatomic, readonly) NSString *blockglideWav; //!< audio/blockglide.wav
@property(nonatomic, readonly) NSString *blocksquishWav; //!< audio/blocksquish.wav
@property(nonatomic, readonly) NSString *blockwallWav; //!< audio/blockwall.wav
@property(nonatomic, readonly) NSString *blockwaterWav; //!< audio/blockwater.wav
@property(nonatomic, readonly) NSString *completedWav; //!< audio/completed.wav
@property(nonatomic, readonly) NSString *eatWav; //!< audio/eat.wav
@property(nonatomic, readonly) NSString *menumusicMp3; //!< audio/menumusic.mp3
@property(nonatomic, readonly) NSString *swooshWav; //!< audio/swoosh.wav
@property(nonatomic, readonly) NSString *walkWav; //!< audio/walk.wav

@end

@interface RGenPathsRootImages : DescriptionString {
  RGenPathsRootTiles *tiles;
}

@property(nonatomic, readonly) NSString *background2xPng; //!< images/background@2x.png
@property(nonatomic, readonly) NSString *background2xipadPng; //!< images/background@2x~ipad.png
@property(nonatomic, readonly) NSString *backgroundPng; //!< images/background.png
@property(nonatomic, readonly) NSString *backgroundipadPng; //!< images/background~ipad.png
@property(nonatomic, readonly) NSString *bigStarsBorderEmpty2xPng; //!< images/big-stars-border-empty@2x.png
@property(nonatomic, readonly) NSString *bigStarsBorderEmpty2xipadPng; //!< images/big-stars-border-empty@2x~ipad.png
@property(nonatomic, readonly) NSString *bigStarsBorderEmptyPng; //!< images/big-stars-border-empty.png
@property(nonatomic, readonly) NSString *bigStarsBorderEmptyipadPng; //!< images/big-stars-border-empty~ipad.png
@property(nonatomic, readonly) NSString *bigStarsBorderFull2xPng; //!< images/big-stars-border-full@2x.png
@property(nonatomic, readonly) NSString *bigStarsBorderFull2xipadPng; //!< images/big-stars-border-full@2x~ipad.png
@property(nonatomic, readonly) NSString *bigStarsBorderFullPng; //!< images/big-stars-border-full.png
@property(nonatomic, readonly) NSString *bigStarsBorderFullipadPng; //!< images/big-stars-border-full~ipad.png
@property(nonatomic, readonly) NSString *bigStarsBorderHalf2xPng; //!< images/big-stars-border-half@2x.png
@property(nonatomic, readonly) NSString *bigStarsBorderHalf2xipadPng; //!< images/big-stars-border-half@2x~ipad.png
@property(nonatomic, readonly) NSString *bigStarsBorderHalfPng; //!< images/big-stars-border-half.png
@property(nonatomic, readonly) NSString *bigStarsBorderHalfipadPng; //!< images/big-stars-border-half~ipad.png
@property(nonatomic, readonly) NSString *bigStarsEmpty2xPng; //!< images/big-stars-empty@2x.png
@property(nonatomic, readonly) NSString *bigStarsEmpty2xipadPng; //!< images/big-stars-empty@2x~ipad.png
@property(nonatomic, readonly) NSString *bigStarsEmptyPng; //!< images/big-stars-empty.png
@property(nonatomic, readonly) NSString *bigStarsEmptyipadPng; //!< images/big-stars-empty~ipad.png
@property(nonatomic, readonly) NSString *bigStarsFull2xPng; //!< images/big-stars-full@2x.png
@property(nonatomic, readonly) NSString *bigStarsFull2xipadPng; //!< images/big-stars-full@2x~ipad.png
@property(nonatomic, readonly) NSString *bigStarsFullPng; //!< images/big-stars-full.png
@property(nonatomic, readonly) NSString *bigStarsFullipadPng; //!< images/big-stars-full~ipad.png
@property(nonatomic, readonly) NSString *bigStarsHalf2xPng; //!< images/big-stars-half@2x.png
@property(nonatomic, readonly) NSString *bigStarsHalf2xipadPng; //!< images/big-stars-half@2x~ipad.png
@property(nonatomic, readonly) NSString *bigStarsHalfPng; //!< images/big-stars-half.png
@property(nonatomic, readonly) NSString *bigStarsHalfipadPng; //!< images/big-stars-half~ipad.png
@property(nonatomic, readonly) NSString *block2xPng; //!< images/block@2x.png
@property(nonatomic, readonly) NSString *block2xipadPng; //!< images/block@2x~ipad.png
@property(nonatomic, readonly) NSString *blockPng; //!< images/block.png
@property(nonatomic, readonly) NSString *blockipadPng; //!< images/block~ipad.png
@property(nonatomic, readonly) NSString *check2xPng; //!< images/check@2x.png
@property(nonatomic, readonly) NSString *check2xipadPng; //!< images/check@2x~ipad.png
@property(nonatomic, readonly) NSString *checkPng; //!< images/check.png
@property(nonatomic, readonly) NSString *checkipadPng; //!< images/check~ipad.png
@property(nonatomic, readonly) NSString *close2xPng; //!< images/close@2x.png
@property(nonatomic, readonly) NSString *close2xipadPng; //!< images/close@2x~ipad.png
@property(nonatomic, readonly) NSString *closePng; //!< images/close.png
@property(nonatomic, readonly) NSString *closeipadPng; //!< images/close~ipad.png
@property(nonatomic, readonly) NSString *community2xPng; //!< images/community@2x.png
@property(nonatomic, readonly) NSString *community2xipadPng; //!< images/community@2x~ipad.png
@property(nonatomic, readonly) NSString *communityPng; //!< images/community.png
@property(nonatomic, readonly) NSString *communityipadPng; //!< images/community~ipad.png
@property(nonatomic, readonly) NSString *completed2xPng; //!< images/completed@2x.png
@property(nonatomic, readonly) NSString *completed2xipadPng; //!< images/completed@2x~ipad.png
@property(nonatomic, readonly) NSString *completedPng; //!< images/completed.png
@property(nonatomic, readonly) NSString *completedipadPng; //!< images/completed~ipad.png
@property(nonatomic, readonly) NSString *delete2xPng; //!< images/delete@2x.png
@property(nonatomic, readonly) NSString *delete2xipadPng; //!< images/delete@2x~ipad.png
@property(nonatomic, readonly) NSString *deletePng; //!< images/delete.png
@property(nonatomic, readonly) NSString *deleteipadPng; //!< images/delete~ipad.png
@property(nonatomic, readonly) NSString *disable2xPng; //!< images/disable@2x.png
@property(nonatomic, readonly) NSString *disable2xipadPng; //!< images/disable@2x~ipad.png
@property(nonatomic, readonly) NSString *disablePng; //!< images/disable.png
@property(nonatomic, readonly) NSString *disableipadPng; //!< images/disable~ipad.png
@property(nonatomic, readonly) NSString *dot2xPng; //!< images/dot@2x.png
@property(nonatomic, readonly) NSString *dot2xipadPng; //!< images/dot@2x~ipad.png
@property(nonatomic, readonly) NSString *dotPng; //!< images/dot.png
@property(nonatomic, readonly) NSString *dotipadPng; //!< images/dot~ipad.png
@property(nonatomic, readonly) NSString *download2xPng; //!< images/download@2x.png
@property(nonatomic, readonly) NSString *download2xipadPng; //!< images/download@2x~ipad.png
@property(nonatomic, readonly) NSString *downloadPng; //!< images/download.png
@property(nonatomic, readonly) NSString *downloadRain2xPng; //!< images/download-rain@2x.png
@property(nonatomic, readonly) NSString *downloadRain2xipadPng; //!< images/download-rain@2x~ipad.png
@property(nonatomic, readonly) NSString *downloadRainPng; //!< images/download-rain.png
@property(nonatomic, readonly) NSString *downloadRainipadPng; //!< images/download-rain~ipad.png
@property(nonatomic, readonly) NSString *downloadSun2xPng; //!< images/download-sun@2x.png
@property(nonatomic, readonly) NSString *downloadSun2xipadPng; //!< images/download-sun@2x~ipad.png
@property(nonatomic, readonly) NSString *downloadSunPng; //!< images/download-sun.png
@property(nonatomic, readonly) NSString *downloadSunipadPng; //!< images/download-sun~ipad.png
@property(nonatomic, readonly) NSString *downloadipadPng; //!< images/download~ipad.png
@property(nonatomic, readonly) NSString *dpad2xPng; //!< images/dpad@2x.png
@property(nonatomic, readonly) NSString *dpad2xipadPng; //!< images/dpad@2x~ipad.png
@property(nonatomic, readonly) NSString *dpadIcon2xPng; //!< images/dpad-icon@2x.png
@property(nonatomic, readonly) NSString *dpadIcon2xipadPng; //!< images/dpad-icon@2x~ipad.png
@property(nonatomic, readonly) NSString *dpadIconPng; //!< images/dpad-icon.png
@property(nonatomic, readonly) NSString *dpadIconipadPng; //!< images/dpad-icon~ipad.png
@property(nonatomic, readonly) NSString *dpadPng; //!< images/dpad.png
@property(nonatomic, readonly) NSString *dpadTouch2xPng; //!< images/dpad-touch@2x.png
@property(nonatomic, readonly) NSString *dpadTouch2xipadPng; //!< images/dpad-touch@2x~ipad.png
@property(nonatomic, readonly) NSString *dpadTouchPng; //!< images/dpad-touch.png
@property(nonatomic, readonly) NSString *dpadTouchipadPng; //!< images/dpad-touch~ipad.png
@property(nonatomic, readonly) NSString *dpadipadPng; //!< images/dpad~ipad.png
@property(nonatomic, readonly) NSString *effect2xPng; //!< images/effect@2x.png
@property(nonatomic, readonly) NSString *effect2xipadPng; //!< images/effect@2x~ipad.png
@property(nonatomic, readonly) NSString *effectPng; //!< images/effect.png
@property(nonatomic, readonly) NSString *effectipadPng; //!< images/effect~ipad.png
@property(nonatomic, readonly) NSString *erase2xPng; //!< images/erase@2x.png
@property(nonatomic, readonly) NSString *erase2xipadPng; //!< images/erase@2x~ipad.png
@property(nonatomic, readonly) NSString *erasePng; //!< images/erase.png
@property(nonatomic, readonly) NSString *eraseipadPng; //!< images/erase~ipad.png
@property(nonatomic, readonly) NSString *handPoint2xPng; //!< images/hand-point@2x.png
@property(nonatomic, readonly) NSString *handPoint2xipadPng; //!< images/hand-point@2x~ipad.png
@property(nonatomic, readonly) NSString *handPointPng; //!< images/hand-point.png
@property(nonatomic, readonly) NSString *handPointipadPng; //!< images/hand-point~ipad.png
@property(nonatomic, readonly) NSString *handTouch2xPng; //!< images/hand-touch@2x.png
@property(nonatomic, readonly) NSString *handTouch2xipadPng; //!< images/hand-touch@2x~ipad.png
@property(nonatomic, readonly) NSString *handTouchPng; //!< images/hand-touch.png
@property(nonatomic, readonly) NSString *handTouchipadPng; //!< images/hand-touch~ipad.png
@property(nonatomic, readonly) NSString *left2xPng; //!< images/left@2x.png
@property(nonatomic, readonly) NSString *left2xipadPng; //!< images/left@2x~ipad.png
@property(nonatomic, readonly) NSString *leftPng; //!< images/left.png
@property(nonatomic, readonly) NSString *leftipadPng; //!< images/left~ipad.png
@property(nonatomic, readonly) NSString *menuAbout2xPng; //!< images/menu-about@2x.png
@property(nonatomic, readonly) NSString *menuAbout2xipadPng; //!< images/menu-about@2x~ipad.png
@property(nonatomic, readonly) NSString *menuAboutPng; //!< images/menu-about.png
@property(nonatomic, readonly) NSString *menuAboutipadPng; //!< images/menu-about~ipad.png
@property(nonatomic, readonly) NSString *menuOverlay2xPng; //!< images/menu-overlay@2x.png
@property(nonatomic, readonly) NSString *menuOverlay2xipadPng; //!< images/menu-overlay@2x~ipad.png
@property(nonatomic, readonly) NSString *menuOverlayPng; //!< images/menu-overlay.png
@property(nonatomic, readonly) NSString *menuOverlayipadPng; //!< images/menu-overlay~ipad.png
@property(nonatomic, readonly) NSString *menuPlay2xPng; //!< images/menu-play@2x.png
@property(nonatomic, readonly) NSString *menuPlay2xipadPng; //!< images/menu-play@2x~ipad.png
@property(nonatomic, readonly) NSString *menuPlayPng; //!< images/menu-play.png
@property(nonatomic, readonly) NSString *menuPlayipadPng; //!< images/menu-play~ipad.png
@property(nonatomic, readonly) NSString *menuSlippy2xPng; //!< images/menu-slippy@2x.png
@property(nonatomic, readonly) NSString *menuSlippy2xipadPng; //!< images/menu-slippy@2x~ipad.png
@property(nonatomic, readonly) NSString *menuSlippyBlink2xPng; //!< images/menu-slippy-blink@2x.png
@property(nonatomic, readonly) NSString *menuSlippyBlink2xipadPng; //!< images/menu-slippy-blink@2x~ipad.png
@property(nonatomic, readonly) NSString *menuSlippyBlinkPng; //!< images/menu-slippy-blink.png
@property(nonatomic, readonly) NSString *menuSlippyBlinkipadPng; //!< images/menu-slippy-blink~ipad.png
@property(nonatomic, readonly) NSString *menuSlippyPng; //!< images/menu-slippy.png
@property(nonatomic, readonly) NSString *menuSlippyipadPng; //!< images/menu-slippy~ipad.png
@property(nonatomic, readonly) NSString *menuTutorial2xPng; //!< images/menu-tutorial@2x.png
@property(nonatomic, readonly) NSString *menuTutorial2xipadPng; //!< images/menu-tutorial@2x~ipad.png
@property(nonatomic, readonly) NSString *menuTutorialPng; //!< images/menu-tutorial.png
@property(nonatomic, readonly) NSString *menuTutorialipadPng; //!< images/menu-tutorial~ipad.png
@property(nonatomic, readonly) NSString *menuYourLevels2xPng; //!< images/menu-your-levels@2x.png
@property(nonatomic, readonly) NSString *menuYourLevels2xipadPng; //!< images/menu-your-levels@2x~ipad.png
@property(nonatomic, readonly) NSString *menuYourLevelsPng; //!< images/menu-your-levels.png
@property(nonatomic, readonly) NSString *menuYourLevelsipadPng; //!< images/menu-your-levels~ipad.png
@property(nonatomic, readonly) NSString *moveable2xPng; //!< images/moveable@2x.png
@property(nonatomic, readonly) NSString *moveable2xipadPng; //!< images/moveable@2x~ipad.png
@property(nonatomic, readonly) NSString *moveablePng; //!< images/moveable.png
@property(nonatomic, readonly) NSString *moveableipadPng; //!< images/moveable~ipad.png
@property(nonatomic, readonly) NSString *music2xPng; //!< images/music@2x.png
@property(nonatomic, readonly) NSString *music2xipadPng; //!< images/music@2x~ipad.png
@property(nonatomic, readonly) NSString *musicPng; //!< images/music.png
@property(nonatomic, readonly) NSString *musicipadPng; //!< images/music~ipad.png
@property(nonatomic, readonly) NSString *new2xPng; //!< images/new@2x.png
@property(nonatomic, readonly) NSString *new2xipadPng; //!< images/new@2x~ipad.png
@property(nonatomic, readonly) NSString *newPng; //!< images/new.png
@property(nonatomic, readonly) NSString *newipadPng; //!< images/new~ipad.png
@property(nonatomic, readonly) NSString *original2xPng; //!< images/original@2x.png
@property(nonatomic, readonly) NSString *original2xipadPng; //!< images/original@2x~ipad.png
@property(nonatomic, readonly) NSString *originalPng; //!< images/original.png
@property(nonatomic, readonly) NSString *originalipadPng; //!< images/original~ipad.png
@property(nonatomic, readonly) NSString *play2xPng; //!< images/play@2x.png
@property(nonatomic, readonly) NSString *play2xipadPng; //!< images/play@2x~ipad.png
@property(nonatomic, readonly) NSString *playPng; //!< images/play.png
@property(nonatomic, readonly) NSString *player2xPng; //!< images/player@2x.png
@property(nonatomic, readonly) NSString *player2xipadPng; //!< images/player@2x~ipad.png
@property(nonatomic, readonly) NSString *playerFrames2xPng; //!< images/player-frames@2x.png
@property(nonatomic, readonly) NSString *playerFrames2xipadPng; //!< images/player-frames@2x~ipad.png
@property(nonatomic, readonly) NSString *playerFramesPng; //!< images/player-frames.png
@property(nonatomic, readonly) NSString *playerFramesipadPng; //!< images/player-frames~ipad.png
@property(nonatomic, readonly) NSString *playerPng; //!< images/player.png
@property(nonatomic, readonly) NSString *playeripadPng; //!< images/player~ipad.png
@property(nonatomic, readonly) NSString *playipadPng; //!< images/play~ipad.png
@property(nonatomic, readonly) NSString *plus2xPng; //!< images/plus@2x.png
@property(nonatomic, readonly) NSString *plus2xipadPng; //!< images/plus@2x~ipad.png
@property(nonatomic, readonly) NSString *plusPng; //!< images/plus.png
@property(nonatomic, readonly) NSString *plusipadPng; //!< images/plus~ipad.png
@property(nonatomic, readonly) NSString *restart2xPng; //!< images/restart@2x.png
@property(nonatomic, readonly) NSString *restart2xipadPng; //!< images/restart@2x~ipad.png
@property(nonatomic, readonly) NSString *restartPng; //!< images/restart.png
@property(nonatomic, readonly) NSString *restartipadPng; //!< images/restart~ipad.png
@property(nonatomic, readonly) NSString *right2xPng; //!< images/right@2x.png
@property(nonatomic, readonly) NSString *right2xipadPng; //!< images/right@2x~ipad.png
@property(nonatomic, readonly) NSString *rightPng; //!< images/right.png
@property(nonatomic, readonly) NSString *rightipadPng; //!< images/right~ipad.png
@property(nonatomic, readonly) NSString *scaleBars2xPng; //!< images/scale-bars@2x.png
@property(nonatomic, readonly) NSString *scaleBars2xipadPng; //!< images/scale-bars@2x~ipad.png
@property(nonatomic, readonly) NSString *scaleBarsPng; //!< images/scale-bars.png
@property(nonatomic, readonly) NSString *scaleBarsipadPng; //!< images/scale-bars~ipad.png
@property(nonatomic, readonly) NSString *scaleFade2xPng; //!< images/scale-fade@2x.png
@property(nonatomic, readonly) NSString *scaleFade2xipadPng; //!< images/scale-fade@2x~ipad.png
@property(nonatomic, readonly) NSString *scaleFadePng; //!< images/scale-fade.png
@property(nonatomic, readonly) NSString *scaleFadeipadPng; //!< images/scale-fade~ipad.png
@property(nonatomic, readonly) NSString *score2xPng; //!< images/score@2x.png
@property(nonatomic, readonly) NSString *score2xipadPng; //!< images/score@2x~ipad.png
@property(nonatomic, readonly) NSString *scorePng; //!< images/score.png
@property(nonatomic, readonly) NSString *scoreipadPng; //!< images/score~ipad.png
@property(nonatomic, readonly) NSString *slippy2xPng; //!< images/slippy@2x.png
@property(nonatomic, readonly) NSString *slippy2xipadPng; //!< images/slippy@2x~ipad.png
@property(nonatomic, readonly) NSString *slippyPng; //!< images/slippy.png
@property(nonatomic, readonly) NSString *slippyipadPng; //!< images/slippy~ipad.png
@property(nonatomic, readonly) NSString *solid2xPng; //!< images/solid@2x.png
@property(nonatomic, readonly) NSString *solid2xipadPng; //!< images/solid@2x~ipad.png
@property(nonatomic, readonly) NSString *solidPng; //!< images/solid.png
@property(nonatomic, readonly) NSString *solidipadPng; //!< images/solid~ipad.png
@property(nonatomic, readonly) NSString *starsBorderEmpty2xPng; //!< images/stars-border-empty@2x.png
@property(nonatomic, readonly) NSString *starsBorderEmpty2xipadPng; //!< images/stars-border-empty@2x~ipad.png
@property(nonatomic, readonly) NSString *starsBorderEmptyPng; //!< images/stars-border-empty.png
@property(nonatomic, readonly) NSString *starsBorderEmptyipadPng; //!< images/stars-border-empty~ipad.png
@property(nonatomic, readonly) NSString *starsBorderFull2xPng; //!< images/stars-border-full@2x.png
@property(nonatomic, readonly) NSString *starsBorderFull2xipadPng; //!< images/stars-border-full@2x~ipad.png
@property(nonatomic, readonly) NSString *starsBorderFullPng; //!< images/stars-border-full.png
@property(nonatomic, readonly) NSString *starsBorderFullipadPng; //!< images/stars-border-full~ipad.png
@property(nonatomic, readonly) NSString *starsBorderHalf2xPng; //!< images/stars-border-half@2x.png
@property(nonatomic, readonly) NSString *starsBorderHalf2xipadPng; //!< images/stars-border-half@2x~ipad.png
@property(nonatomic, readonly) NSString *starsBorderHalfPng; //!< images/stars-border-half.png
@property(nonatomic, readonly) NSString *starsBorderHalfipadPng; //!< images/stars-border-half~ipad.png
@property(nonatomic, readonly) NSString *starsEmpty2xPng; //!< images/stars-empty@2x.png
@property(nonatomic, readonly) NSString *starsEmpty2xipadPng; //!< images/stars-empty@2x~ipad.png
@property(nonatomic, readonly) NSString *starsEmptyPng; //!< images/stars-empty.png
@property(nonatomic, readonly) NSString *starsEmptyipadPng; //!< images/stars-empty~ipad.png
@property(nonatomic, readonly) NSString *starsFull2xPng; //!< images/stars-full@2x.png
@property(nonatomic, readonly) NSString *starsFull2xipadPng; //!< images/stars-full@2x~ipad.png
@property(nonatomic, readonly) NSString *starsFullPng; //!< images/stars-full.png
@property(nonatomic, readonly) NSString *starsFullipadPng; //!< images/stars-full~ipad.png
@property(nonatomic, readonly) NSString *starsHalf2xPng; //!< images/stars-half@2x.png
@property(nonatomic, readonly) NSString *starsHalf2xipadPng; //!< images/stars-half@2x~ipad.png
@property(nonatomic, readonly) NSString *starsHalfPng; //!< images/stars-half.png
@property(nonatomic, readonly) NSString *starsHalfipadPng; //!< images/stars-half~ipad.png
@property(nonatomic, readonly) RGenPathsRootTiles *tiles; //!< images/tiles
@property(nonatomic, readonly) NSString *undo2xPng; //!< images/undo@2x.png
@property(nonatomic, readonly) NSString *undo2xipadPng; //!< images/undo@2x~ipad.png
@property(nonatomic, readonly) NSString *undoPng; //!< images/undo.png
@property(nonatomic, readonly) NSString *undoipadPng; //!< images/undo~ipad.png
@property(nonatomic, readonly) NSString *upload2xPng; //!< images/upload@2x.png
@property(nonatomic, readonly) NSString *upload2xipadPng; //!< images/upload@2x~ipad.png
@property(nonatomic, readonly) NSString *uploadCheck2xPng; //!< images/upload-check@2x.png
@property(nonatomic, readonly) NSString *uploadCheck2xipadPng; //!< images/upload-check@2x~ipad.png
@property(nonatomic, readonly) NSString *uploadCheckPng; //!< images/upload-check.png
@property(nonatomic, readonly) NSString *uploadCheckipadPng; //!< images/upload-check~ipad.png
@property(nonatomic, readonly) NSString *uploadPng; //!< images/upload.png
@property(nonatomic, readonly) NSString *uploadRain2xPng; //!< images/upload-rain@2x.png
@property(nonatomic, readonly) NSString *uploadRain2xipadPng; //!< images/upload-rain@2x~ipad.png
@property(nonatomic, readonly) NSString *uploadRainPng; //!< images/upload-rain.png
@property(nonatomic, readonly) NSString *uploadRainipadPng; //!< images/upload-rain~ipad.png
@property(nonatomic, readonly) NSString *uploadSun2xPng; //!< images/upload-sun@2x.png
@property(nonatomic, readonly) NSString *uploadSun2xipadPng; //!< images/upload-sun@2x~ipad.png
@property(nonatomic, readonly) NSString *uploadSunPng; //!< images/upload-sun.png
@property(nonatomic, readonly) NSString *uploadSunipadPng; //!< images/upload-sun~ipad.png
@property(nonatomic, readonly) NSString *uploadipadPng; //!< images/upload~ipad.png
@property(nonatomic, readonly) NSString *water2xPng; //!< images/water@2x.png
@property(nonatomic, readonly) NSString *water2xipadPng; //!< images/water@2x~ipad.png
@property(nonatomic, readonly) NSString *waterPng; //!< images/water.png
@property(nonatomic, readonly) NSString *wateripadPng; //!< images/water~ipad.png

@end

@interface RGenPathsRootTiles : DescriptionString {
  RGenPathsRootImagesNormal *normal;
  RGenPathsRootImagesPreview *preview;
}

@property(nonatomic, readonly) RGenPathsRootImagesNormal *normal; //!< images/tiles/normal
@property(nonatomic, readonly) RGenPathsRootImagesPreview *preview; //!< images/tiles/preview

@end

@interface RGenPathsRootImagesNormal : DescriptionString
@property(nonatomic, readonly) NSString *block2xPng; //!< images/tiles/normal/block@2x.png
@property(nonatomic, readonly) NSString *block2xipadPng; //!< images/tiles/normal/block@2x~ipad.png
@property(nonatomic, readonly) NSString *blockMask2xPng; //!< images/tiles/normal/block-mask@2x.png
@property(nonatomic, readonly) NSString *blockMask2xipadPng; //!< images/tiles/normal/block-mask@2x~ipad.png
@property(nonatomic, readonly) NSString *blockMaskPng; //!< images/tiles/normal/block-mask.png
@property(nonatomic, readonly) NSString *blockMaskipadPng; //!< images/tiles/normal/block-mask~ipad.png
@property(nonatomic, readonly) NSString *blockPng; //!< images/tiles/normal/block.png
@property(nonatomic, readonly) NSString *blockipadPng; //!< images/tiles/normal/block~ipad.png
@property(nonatomic, readonly) NSString *moveable2xPng; //!< images/tiles/normal/moveable@2x.png
@property(nonatomic, readonly) NSString *moveable2xipadPng; //!< images/tiles/normal/moveable@2x~ipad.png
@property(nonatomic, readonly) NSString *moveablePng; //!< images/tiles/normal/moveable.png
@property(nonatomic, readonly) NSString *moveableipadPng; //!< images/tiles/normal/moveable~ipad.png
@property(nonatomic, readonly) NSString *player2xPng; //!< images/tiles/normal/player@2x.png
@property(nonatomic, readonly) NSString *player2xipadPng; //!< images/tiles/normal/player@2x~ipad.png
@property(nonatomic, readonly) NSString *playerPng; //!< images/tiles/normal/player.png
@property(nonatomic, readonly) NSString *playeripadPng; //!< images/tiles/normal/player~ipad.png
@property(nonatomic, readonly) NSString *score2xPng; //!< images/tiles/normal/score@2x.png
@property(nonatomic, readonly) NSString *score2xipadPng; //!< images/tiles/normal/score@2x~ipad.png
@property(nonatomic, readonly) NSString *scorePng; //!< images/tiles/normal/score.png
@property(nonatomic, readonly) NSString *scoreipadPng; //!< images/tiles/normal/score~ipad.png
@property(nonatomic, readonly) NSString *solid2xPng; //!< images/tiles/normal/solid@2x.png
@property(nonatomic, readonly) NSString *solid2xipadPng; //!< images/tiles/normal/solid@2x~ipad.png
@property(nonatomic, readonly) NSString *solidPng; //!< images/tiles/normal/solid.png
@property(nonatomic, readonly) NSString *solidipadPng; //!< images/tiles/normal/solid~ipad.png

@end

@interface RGenPathsRootImagesPreview : DescriptionString
@property(nonatomic, readonly) NSString *block2xPng; //!< images/tiles/preview/block@2x.png
@property(nonatomic, readonly) NSString *block2xipadPng; //!< images/tiles/preview/block@2x~ipad.png
@property(nonatomic, readonly) NSString *blockPng; //!< images/tiles/preview/block.png
@property(nonatomic, readonly) NSString *blockipadPng; //!< images/tiles/preview/block~ipad.png
@property(nonatomic, readonly) NSString *moveable2xPng; //!< images/tiles/preview/moveable@2x.png
@property(nonatomic, readonly) NSString *moveable2xipadPng; //!< images/tiles/preview/moveable@2x~ipad.png
@property(nonatomic, readonly) NSString *moveablePng; //!< images/tiles/preview/moveable.png
@property(nonatomic, readonly) NSString *moveableipadPng; //!< images/tiles/preview/moveable~ipad.png
@property(nonatomic, readonly) NSString *player2xPng; //!< images/tiles/preview/player@2x.png
@property(nonatomic, readonly) NSString *player2xipadPng; //!< images/tiles/preview/player@2x~ipad.png
@property(nonatomic, readonly) NSString *playerPng; //!< images/tiles/preview/player.png
@property(nonatomic, readonly) NSString *playeripadPng; //!< images/tiles/preview/player~ipad.png
@property(nonatomic, readonly) NSString *score2xPng; //!< images/tiles/preview/score@2x.png
@property(nonatomic, readonly) NSString *score2xipadPng; //!< images/tiles/preview/score@2x~ipad.png
@property(nonatomic, readonly) NSString *scorePng; //!< images/tiles/preview/score.png
@property(nonatomic, readonly) NSString *scoreipadPng; //!< images/tiles/preview/score~ipad.png
@property(nonatomic, readonly) NSString *solid2xPng; //!< images/tiles/preview/solid@2x.png
@property(nonatomic, readonly) NSString *solid2xipadPng; //!< images/tiles/preview/solid@2x~ipad.png
@property(nonatomic, readonly) NSString *solidPng; //!< images/tiles/preview/solid.png
@property(nonatomic, readonly) NSString *solidipadPng; //!< images/tiles/preview/solid~ipad.png

@end

@interface RGenPathsRootLevels : DescriptionString
@property(nonatomic, readonly) NSString *originalLevelsPlist; //!< levels/OriginalLevels.plist
@property(nonatomic, readonly) NSString *tutorialIntroPlist; //!< levels/TutorialIntro.plist
@property(nonatomic, readonly) NSString *tutorialLevelsPlist; //!< levels/TutorialLevels.plist
@property(nonatomic, readonly) NSString *tutorialMove1Plist; //!< levels/TutorialMove1.plist
@property(nonatomic, readonly) NSString *tutorialMove2Plist; //!< levels/TutorialMove2.plist
@property(nonatomic, readonly) NSString *tutorialPush1Plist; //!< levels/TutorialPush1.plist
@property(nonatomic, readonly) NSString *tutorialPush2Plist; //!< levels/TutorialPush2.plist
@property(nonatomic, readonly) NSString *tutorialRestartPlist; //!< levels/TutorialRestart.plist
@property(nonatomic, readonly) NSString *tutorialScoreBlockPlist; //!< levels/TutorialScoreBlock.plist
@property(nonatomic, readonly) NSString *tutorialWorld1Plist; //!< levels/TutorialWorld1.plist
@property(nonatomic, readonly) NSString *tutorialWorld2Plist; //!< levels/TutorialWorld2.plist

@end

@interface RGenPathsRootSettingsbundle : DescriptionString {
  RGenPathsRootEnlproj *enLproj;
}

@property(nonatomic, readonly) RGenPathsRootEnlproj *enLproj; //!< Settings.bundle/en.lproj
@property(nonatomic, readonly) NSString *rootPlist; //!< Settings.bundle/Root.plist

@end

@interface RGenPathsRootEnlproj : DescriptionString
@property(nonatomic, readonly) NSString *rootStrings; //!< Settings.bundle/en.lproj/Root.strings

@end

